// algo-bot/services/data-service/src/clients/UpstoxFeedClient.ts

import WebSocket from 'ws';
import { EventEmitter } from 'events';
import { decodeMarketFeed } from '../utils/protobufDecoder';
import { RedisEventBus, EventTopic } from '@algo-bot/shared';

export class UpstoxFeedClient extends EventEmitter {
    private ws: WebSocket | null = null;
    private url: string;
    private redisBus: RedisEventBus;

    constructor(url: string) {
        super();
        this.url = url;
        this.redisBus = new RedisEventBus();
    }

    public connect(): void {
        console.log('[UpstoxFeedClient] Initiating WebSocket connection...');
        
        // Connect to the dynamic, one-time URL generated by Upstox
        this.ws = new WebSocket(this.url);

        this.ws.on('open', () => {
            console.log('[UpstoxFeedClient] WebSocket connected.');
            this.emit('connected');
        });

        this.ws.on('close', () => {
            console.log('[UpstoxFeedClient] WebSocket closed.');
            this.emit('disconnected');
        });

        this.ws.on('error', (error: Error) => {
            console.error('[UpstoxFeedClient] WebSocket Error:', error.message);
            this.emit('error', error);
        });

        // The core data pipeline: Catching binary -> Decoding -> Publishing
        this.ws.on('message', async (data: Buffer) => {
            try {
                // 1. Decode the binary Protocol Buffer data
                const decodedData = decodeMarketFeed(data);
                
                // If it's empty or a keep-alive ping, ignore it
                if (!decodedData || !decodedData.feeds) return;

                // 2. Loop through every instrument in the payload
                for (const [instrumentToken, feedData] of Object.entries(decodedData.feeds)) {
                    const feed = feedData as any;
                    
                    // 3. Extract the Last Traded Price based on the feed type
                    let ltp = 0;
                    if (feed.ltpc?.ltp) ltp = feed.ltpc.ltp;
                    else if (feed.fullFeed?.marketFF?.ltp) ltp = feed.fullFeed.marketFF.ltp;
                    else if (feed.indexFF?.marketFF?.ltp) ltp = feed.indexFF.marketFF.ltp;

                    if (ltp > 0) {
                        // 4. Format the tick to our standard internal system contract
                        const marketTick = {
                            instrumentToken: instrumentToken,
                            lastTradedPrice: ltp,
                            timestamp: Date.now()
                        };

                        // 5. Blast it across the Redis bus to the Python Strategy Engine
                        await this.redisBus.publish(EventTopic.MARKET_TICK, marketTick);
                        
                        // Debug log (comment this out in production to save CPU cycles)
                        console.log(`[UpstoxFeed] 📈 ${instrumentToken} | LTP: ${ltp}`);
                    }
                }
            } catch (err) {
                console.error('[UpstoxFeedClient] Critical error processing message loop:', err);
            }
        });
    }

    /**
     * Sends a subscription request to the Upstox WebSocket to start streaming data
     * for specific instruments.
     */
    public subscribe(instrumentKeys: string[], mode: 'full' | 'ltpc' = 'full'): void {
        if (!this.ws || this.ws.readyState !== WebSocket.OPEN) {
            console.warn('[UpstoxFeedClient] Cannot subscribe, WebSocket is not open.');
            return;
        }

        // Upstox v3 Subscription Payload Structure
        const payload = {
            guid: "algo-bot-sub-" + Date.now(),
            method: "sub",
            data: {
                mode: mode,
                instrumentKeys: instrumentKeys
            }
        };

        // Upstox requires the payload to be sent as a Buffer of the JSON string
        this.ws.send(Buffer.from(JSON.stringify(payload)));
        console.log(`[UpstoxFeedClient] Requested subscription to ${instrumentKeys.length} instruments.`);
    }

    public disconnect(): void {
        if (this.ws) {
            this.ws.close();
            this.ws = null;
        }
    }
}